version: '3.8'

services:
  book_catalog:
    image: flixtubec2849faf.azurecr.io/book_catalog:latest
    container_name: book_catalog_service
    environment:
      - VERSION=latest
      - CONTAINER_REGISTRY=flixtubec2849faf.azurecr.io
    networks:
      - app-network

  inventory_management:
    image: flixtubec2849faf.azurecr.io/inventory_management:latest
    container_name: inventory_management_service
    environment:
      - VERSION=latest
      - CONTAINER_REGISTRY=flixtubec2849faf.azurecr.io
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
